config/routes.rb
SampleApp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,   only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :authorizations # is this causing the no route matches get... errors?
  root 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match '/auth/failure', to: 'sessions#failure', via: 'get'
  match '/posts', to: 'posts#index', via: 'get'
  match '/posts/new', to: 'posts#new', via: 'get'

  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    include StatsHelper
# the following before_filter makes stats_view method (from stats_helper.rb) available in show.
  before_filter :stats_view,    only: :home

  def home
  	if signed_in?
  		@micropost = current_user.microposts.build
  		@feed_items = current_user.feed.paginate(page: params[:page], per_page: 4)
      # @who is defined for graph displays in _wellness_bar.html.erb
      @who = 'iVolve Index'
      SiteVisit.tracking_model(current_user.id, 'static_home', nil)
    end
  end

  def help
    if signed_in?
      SiteVisit.tracking_model(current_user.id, 'static_help', nil)
    end
  end

  def about
    if signed_in?
      SiteVisit.tracking_model(current_user.id, 'static_about', nil)
    end

  end

  def contact
    if signed_in?
      SiteVisit.tracking_model(current_user.id, 'static_contact', nil)
    end
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>

	<h1>About Us</h1>

	<div class="container">
		<p class="lead text-left"> 
			The modern world is an amazing place. The Internet has placed billions of opportunities at your fingertips; opportunities to learn, opportunities to grow, opportunities to experience life. Every day is an opportunity. There are people to meet, places to see, billions of possibilities to explore in this amazing thing we call life.
		</p>

		<br>
			<p class="lead text-center">
				<strong>This is the inspiration for iVolve.</strong>
			</p>

		<br>
		<p class="lead text-left">
			Get out there and expand your horizons, soak it all in, enjoy yourself. Find something you love. Do it everyday. Do something new everyday. Move, hustle, read, learn, explore. Immerse yourself in life and all it has to offer.
		</p>

		<br>
		<p class="lead text-center">
			<strong>iVolve yourself.</strong>
		</p>
	</div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
	Email: info@ivolve.me
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>

	<h1>Help</h1>
	<p>
		I'll put some directions here eventually?

	</p>

<!-- The following is an example of a button -->

<div class="dropdown">
  <button class="btn dropdown-toggle sr-only" type="button" id="dropdownMenu1" data-toggle="dropdown">
    Dropdown
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Action</a></li>
    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Another action</a></li>
    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Something else here</a></li>
    <li role="presentation" class="divider"></li>
    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Separated link</a></li>
  </ul>
</div>

<button type="button" class="btn btn-default btn-lg">
  <span class="glyphicon glyphicon-star"></span> Star
</button>

app/views/static_pages/home.html.erb
<% if signed_in? %>
	<div class="row">
		<aside class="col-xs-12 col-sm-4">
			<section>
				<%= render 'shared/user_info' %>
			</section>
			<section>
				<%= render 'shared/stats' %>
			</section>
			<section>
				<%= render 'shared/micropost_form' %>
			</section>
		</aside>
			
		<div class="col-xs-12 col-sm-8">		
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">My Apps</h3>
				</div>
				<div class="panel-body">
					<div class="col-xs-6 col-sm-4" style="padding-top: 3px; padding-bottom: 3px">
						<% if linkedin? %>
							<button class="btn btn-primary btn-large active">LinkedIn</button>
						<% else %>
							<%= link_to "Link your LinkedIn!", "/auth/linkedin", class: "btn btn-large btn-danger" %>
						<% end %>
					</div>
					<div class="col-xs-6 col-sm-4" style="padding-top: 3px; padding-bottom: 3px">
						<% if twitter? %>
							<button class="btn btn-primary btn-large active">Twitter</button>
						<% else %>
							<%= link_to "Link your Twitter!", "/auth/twitter?user_authorize=true", class: "btn btn-large btn-danger" %>
						<% end %>
					</div>
					<div class="col-xs-6 col-sm-4" style="padding-top: 3px; padding-bottom: 3px">
						<% if !facebook? || facebook_expired? %>
							<%= link_to "Link your Facebook!", "/auth/facebook", class: "btn btn-large btn-danger" %>
						<% else %>
							<button class="btn btn-primary btn-large active">Facebook</button>
						<% end %>
					</div>
					<div class="col-xs-6 col-sm-4" style="padding-top: 3px; padding-bottom: 3px">
						<% if instagram? %>
							<button class="btn btn-primary btn-large active">Instagram</button>
						<% else %>
							<%= link_to "Link your Instagram!", "/auth/instagram", class: "btn btn-large btn-danger" %>
						<% end %>
					</div>
					<div class="col-xs-6 col-sm-4" style="padding-top: 3px; padding-bottom: 3px">
						<% if foursquare? %>
							<button class="btn btn-primary btn-large active">Foursquare</button>
						<% else %>
							<%= link_to "Link your Foursquare!", "/auth/foursquare", class: "btn btn-large btn-danger" %>
						<% end %>
					</div>
					<div class="col-xs-6 col-sm-4" style="padding-top: 3px; padding-bottom: 3px">
						<% if fitbit? %>
							<button class="btn btn-primary btn-large active">Fitbit</button>
						<% else %>
							<%= link_to "Link your Fitbit!", "/auth/fitbit", class: "btn btn-large btn-danger" %>
						<% end %>
					</div>
				</div>
			</div>
		</div>
				
		<div class="col-xs-12 col-sm-8">	
				<h3>Peanut Gallery</h3>
				<%= render 'shared/feed' %>
		</div>
	</div>

	<div class="row">
				<%= render 'shared/social_connections.html.erb' %>
	</div>
	<div class="row">
				<%= render 'shared/social_connections_time.html.erb' %>
	</div>
	<div class="row">
				<%= render 'shared/social_engagement.html.erb' %>
	</div>
	<div class="row">
				<%= render 'shared/social_output_time.html.erb' %>
	</div>
	<div class="row">
				<%= render 'shared/twitter_followers_following.html.erb' %>
	</div>
	<div class="row">
				<%= render 'shared/twitter_input_vs_output.html.erb' %>
	</div>
	<div class="row">
				<%= render 'shared/user_activity.html.erb' %>
	</div>
<% else %>

	<div class="center jumbotron">
	
		<%= link_to image_tag("ivolvelogo.png", alt: "about-ivolve", class: "center img-responsive"), about_path %>
		<h1 style="color: white;">Welcome to the iVolution!</h1>
	  
		<h2>
			This is the home page for the
	    	<a id="gaLink" href="http://ivolve.me/">iVolve</a> application.
		</h2>

		<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
	</div>

<% end %>