config/routes.rb
SampleApp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,   only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :authorizations # is this causing the no route matches get... errors?
  root 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match '/auth/failure', to: 'sessions#failure', via: 'get'
  match '/posts', to: 'posts#index', via: 'get'
  match '/posts/new', to: 'posts#new', via: 'get'

  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<a id="gaLink" href="http://ivolve.me/">iVolve App</a>
		by the Obvious Ridge Route 
	</small>
	<nav>
		<ul>
			<li><%= link_to "About Us", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
			<li><a id="gaLink" href="http://blog.ivolve.me/">Blog</a></li>
		</ul>
	</nav>
	
<!-- Google Analytics below, placed here to work around turbolinks! -->
	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga(function(tracker) {
  		var linker = new window.gaplugins.Linker(tracker);
  		var output = linker.decorate('//ivolve.me');
	  });
	  ga('create', 'UA-45439646-1', 'auto', {
	  	'allowLinker': true		// Value is retrieved from method above.
	  });
	  ga('require', 'linkid', 'linkid.js');
	  ga('send', 'pageview');


	  /* The following code should track links to other domains.  It looks for the gaLink element id
	  */
	    var linker;

		var gaLink = document.getElementById('gaLink');             // Add event listeners to link.
		addListener(gaLink, 'mousedown', decorateMe);
		addListener(gaLink, 'keydown', decorateMe);

		function decorateMe(event) {
		  event = event || window.event;                            // Cross browser hoops.
		  var target = event.target || event.srcElement;

		  if (target && target.href) {                              // Ensure this is a link.
		    ga('linker:decorate', target);
		  }
		}

		// Cross browser way to listen for events.
		function addListener(element, type, callback) {
		 if (element.addEventListener) element.addEventListener(type, callback);
		 else if (element.attachEvent) element.attachEvent('on' + type, callback);
		}

	</script>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" role="navigation">
	<!-- Brand and toggle get grouped for a better mobile display -->
	<div class="navbar-header">
		<!-- <div class="container"> -->
			<a href="http://ivolve.herokuapp.com" id="logo" class="navbar-brand"><span class="yellow">i</span><span class="green">V</span><span class="blue">o</span><span class="violet">l</span><span class="red">v</span><span class="orange">e</span></a>

			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		      <span class="sr-only">Toggle navigation</span>
		      <span class="icon-bar"></span>
		      <span class="icon-bar"></span>
		      <span class="icon-bar"></span>
		    </button>
			
				<%# id: "logo" above is a css link%>
	</div>
			
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav pull-right">
					<li><%= link_to "Home",		root_path %></li>
					<li><%= link_to "Help", 	help_path %></li>
					<% if signed_in? %>
						<li><%= link_to "Users", users_path %></li>
						<!-- Add My Apps, Friends, Leaders, Activities... -->
						
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown"> <%= gravatar_for(current_user, size: 20) %> <b class="caret"></b>
							</a>
								
							<ul class="dropdown-menu">
								<li>
									<!-- <span style="padding-top: 3px" class="glyphicon glyphicon-user"> -->
									<%= link_to "Profile", current_user %>
								</li>

								<li>
									<!-- <span class="glyphicon glyphicon-wrench"> -->
									<%= link_to "Settings", edit_user_path(current_user) %>
								</li>
								
								<li class="divider"></li>

								<li>
									<!-- <span class="glyphicon glyphicon-off"> -->
									<%= link_to "Sign out", signout_path, method: "delete" %>
								</li>
							</ul>
						</li>
					<% else %>
						<li><%= link_to "Sign in", 	signin_path %></li>
					<% end %>
				</ul>

			</div> 
</header>

app/views/layouts/_shim.html.erb
 	 <!--[if lt IE 9]>
 	 <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
 	 <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

	<head>
		<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
	  	<title><%= full_title(yield(:title)) %></title>
	  	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>

	 	 <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	 	 <%= csrf_meta_tags %>
	 	 <%= favicon_link_tag 'favicon.ico' %>
	 	 <%= render 'layouts/shim' %>
	</head>

	<body>
	<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |key, value| %>
				<%= content_tag(:div, value, class: "alert alert-#{key}") %>
			<% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>

</html>